// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: extra_proxies.sql

package extra_proxies_queries

import (
	"context"
)

const listExtraProxies = `-- name: ListExtraProxies :many
SELECT proxy_link
FROM extra_proxies
`

func (q *Queries) ListExtraProxies(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExtraProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var proxy_link string
		if err := rows.Scan(&proxy_link); err != nil {
			return nil, err
		}
		items = append(items, proxy_link)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
