// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package extra_proxies_queries

import (
	"context"
)

type Querier interface {
	ListExtraProxies(ctx context.Context) ([]string, error)
}

var _ Querier = (*Queries)(nil)
