// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"context"
	"net"

	"go.redsock.ru/rerrors"

	"go.redsock.ru/mead/internal/server"
	"go.redsock.ru/mead/internal/service"
	"go.redsock.ru/mead/internal/service/iservice"
	"go.redsock.ru/mead/internal/storage"
	"go.redsock.ru/mead/internal/storage/sqlite"
	"go.redsock.ru/mead/internal/transport"
)

type Custom struct {
	SqliteStorage storage.Storage

	Service iservice.Service

	ProxyServer *server.Server
	ApiServer   *transport.ServersManager
}

func (c *Custom) Init(a *App) (err error) {
	c.SqliteStorage = sqlite.New(a.Sqlite)

	c.Service = service.New(c.SqliteStorage)

	c.ProxyServer, err = server.New(a.Cfg, c.Service)
	if err != nil {
		return rerrors.Wrap(err, "init custom server")
	}

	c.ApiServer, err = transport.NewServerManager(a.Ctx, a.ServerMaster)

	return nil
}

func (c *Custom) Start(ctx context.Context) error {
	err := c.ProxyServer.ListenAndServe(ctx)
	if err != nil {
		return rerrors.Wrap(err, "start custom server")
	}

	return nil
}

func (c *Custom) Stop() error {
	err := c.ProxyServer.Close()
	if err != nil {
		return rerrors.Wrap(err, "close custom server")
	}

	return nil
}
