// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"context"

	"go.redsock.ru/rerrors"
	"golang.org/x/sync/errgroup"

	"go.redsock.ru/mead/internal/middleware"
	"go.redsock.ru/mead/internal/server"
	"go.redsock.ru/mead/internal/service"
	"go.redsock.ru/mead/internal/service/iservice"
	"go.redsock.ru/mead/internal/storage"
	"go.redsock.ru/mead/internal/storage/sqlite"
	"go.redsock.ru/mead/internal/transport"
	"go.redsock.ru/mead/internal/transport/mead_api_impl"
	"go.redsock.ru/mead/internal/transport/telegram"
	"go.redsock.ru/mead/pkg/docs"
)

type Custom struct {
	SqliteStorage storage.Storage

	Service iservice.Service

	ApiServer   *transport.ServersManager
	ProxyServer *server.Server
	TgServer    *telegram.Server
}

func (c *Custom) Init(a *App) (err error) {
	c.SqliteStorage = sqlite.New(a.Sqlite)

	c.Service = service.New(a.Cfg, c.SqliteStorage)

	c.ProxyServer, err = server.New(a.Cfg, c.Service)
	if err != nil {
		return rerrors.Wrap(err, "init proxy server")
	}

	c.ApiServer, err = transport.NewServerManager(a.Ctx, a.MASTER)
	if err != nil {
		return rerrors.Wrap(err, "init api server")
	}

	c.ApiServer.AddHttpHandler(docs.Swagger())
	c.ApiServer.AddImplementation(mead_api_impl.New(a.Cfg, c.Service))

	c.ApiServer.AddServerOption(
		middleware.AuthInterceptor("123"),
		middleware.LogInterceptor(),
		middleware.PanicInterceptor(),
	)

	c.TgServer = telegram.NewServer(a.Cfg, a.Telegram, c.Service)
	return nil
}

func (c *Custom) Start(ctx context.Context) error {
	eg, ctx := errgroup.WithContext(ctx)

	eg.Go(func() error {
		return c.ProxyServer.ListenAndServe(ctx)
	})
	eg.Go(c.ApiServer.Start)
	eg.Go(c.TgServer.Start)

	err := eg.Wait()
	if err != nil {
		return rerrors.Wrap(err)
	}

	return nil
}

func (c *Custom) Stop() error {

	eg := errgroup.Group{}
	eg.Go(c.ProxyServer.Close)
	eg.Go(c.ApiServer.Stop)
	eg.Go(c.TgServer.Stop)

	return nil
}
