### Create one user
POST {{url}}/api/user
Content-Type: application/json
Authorization: Pass {{token}}

{
  "username": "AlexSkilled"
}


### Create one user
POST {{url}}/api/user
Content-Type: application/json
Authorization: Pass {{token}}

{
  "usernames": {
    "usernames": [
      "AlexSkilled"
    ]
  }
}
