// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_queries

import (
	"database/sql"
)

type User struct {
	Username   string
	Pass       string
	TelegramID sql.NullInt64
}

type UserStatistic struct {
	Username    string
	LastConnect sql.NullTime
	BytesPassed sql.NullInt64
}
