// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_queries

import (
	"context"
	"database/sql"
)

type Querier interface {
	Add(ctx context.Context, arg AddParams) error
	GetByTelegramId(ctx context.Context, telegramID sql.NullInt64) (GetByTelegramIdRow, error)
	GetByTelegramName(ctx context.Context, username string) (GetByTelegramNameRow, error)
	GetPassByUsername(ctx context.Context, username string) (string, error)
	ListStatistics(ctx context.Context) ([]UserStatistic, error)
	UpdateStatistics(ctx context.Context, arg UpdateStatisticsParams) error
}

var _ Querier = (*Queries)(nil)
