// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_queries

import (
	"context"
)

type Querier interface {
	Add(ctx context.Context, arg AddParams) error
	GetByTelegramName(ctx context.Context, username string) (string, error)
	GetPassByUsername(ctx context.Context, username string) (string, error)
}

var _ Querier = (*Queries)(nil)
