// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_queries

import (
	"context"
)

type Querier interface {
	Add(ctx context.Context, arg AddParams) error
}

var _ Querier = (*Queries)(nil)
