// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package user_queries

import (
	"context"
	"database/sql"
)

const add = `-- name: Add :exec
INSERT INTO users (username, pass, telegram_id)
VALUES (?, ?, ?)
`

type AddParams struct {
	Username   string
	Pass       string
	TelegramID sql.NullInt64
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.ExecContext(ctx, add, arg.Username, arg.Pass, arg.TelegramID)
	return err
}

const getByTelegramId = `-- name: GetByTelegramId :one
SELECT username, telegram_id
FROM users
WHERE telegram_id = ?
LIMIT 1
`

type GetByTelegramIdRow struct {
	Username   string
	TelegramID sql.NullInt64
}

func (q *Queries) GetByTelegramId(ctx context.Context, telegramID sql.NullInt64) (GetByTelegramIdRow, error) {
	row := q.db.QueryRowContext(ctx, getByTelegramId, telegramID)
	var i GetByTelegramIdRow
	err := row.Scan(&i.Username, &i.TelegramID)
	return i, err
}

const getByTelegramName = `-- name: GetByTelegramName :one
SELECT username, telegram_id
FROM users
WHERE username = ?
LIMIT 1
`

type GetByTelegramNameRow struct {
	Username   string
	TelegramID sql.NullInt64
}

func (q *Queries) GetByTelegramName(ctx context.Context, username string) (GetByTelegramNameRow, error) {
	row := q.db.QueryRowContext(ctx, getByTelegramName, username)
	var i GetByTelegramNameRow
	err := row.Scan(&i.Username, &i.TelegramID)
	return i, err
}

const getPassByUsername = `-- name: GetPassByUsername :one
SELECT pass
FROM users
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetPassByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPassByUsername, username)
	var pass string
	err := row.Scan(&pass)
	return pass, err
}

const listStatistics = `-- name: ListStatistics :many
SELECT username, last_connect, bytes_passed
FROM user_statistics
`

func (q *Queries) ListStatistics(ctx context.Context) ([]UserStatistic, error) {
	rows, err := q.db.QueryContext(ctx, listStatistics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserStatistic{}
	for rows.Next() {
		var i UserStatistic
		if err := rows.Scan(&i.Username, &i.LastConnect, &i.BytesPassed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatistics = `-- name: UpdateStatistics :exec
INSERT INTO user_statistics (username, last_connect, bytes_passed)
VALUES (?, CURRENT_TIMESTAMP, ?)
ON CONFLICT(username) DO UPDATE SET
    last_connect = excluded.last_connect,
    bytes_passed = user_statistics.bytes_passed + excluded.bytes_passed
`

type UpdateStatisticsParams struct {
	Username    string
	BytesPassed sql.NullInt64
}

func (q *Queries) UpdateStatistics(ctx context.Context, arg UpdateStatisticsParams) error {
	_, err := q.db.ExecContext(ctx, updateStatistics, arg.Username, arg.BytesPassed)
	return err
}
