// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package user_queries

import (
	"context"
)

const add = `-- name: Add :exec
INSERT INTO users (username, pass)
VALUES (?, ?)
`

type AddParams struct {
	Username string
	Pass     string
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.ExecContext(ctx, add, arg.Username, arg.Pass)
	return err
}
