// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package user_queries

import (
	"context"
)

const add = `-- name: Add :exec
INSERT INTO users (username, pass)
VALUES (?, ?)
`

type AddParams struct {
	Username string
	Pass     string
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.ExecContext(ctx, add, arg.Username, arg.Pass)
	return err
}

const getByTelegramName = `-- name: GetByTelegramName :one
SELECT username
FROM users
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetByTelegramName(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getByTelegramName, username)
	err := row.Scan(&username)
	return username, err
}

const getPassByUsername = `-- name: GetPassByUsername :one
SELECT pass
FROM users
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetPassByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPassByUsername, username)
	var pass string
	err := row.Scan(&pass)
	return pass, err
}
