// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: mead_api.proto

package mead_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeadAPI_Version_FullMethodName = "/mead_api.MeadAPI/Version"
)

// MeadAPIClient is the client API for MeadAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeadAPIClient interface {
	Version(ctx context.Context, in *Version_Request, opts ...grpc.CallOption) (*Version_Response, error)
}

type meadAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewMeadAPIClient(cc grpc.ClientConnInterface) MeadAPIClient {
	return &meadAPIClient{cc}
}

func (c *meadAPIClient) Version(ctx context.Context, in *Version_Request, opts ...grpc.CallOption) (*Version_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Version_Response)
	err := c.cc.Invoke(ctx, MeadAPI_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeadAPIServer is the server API for MeadAPI service.
// All implementations must embed UnimplementedMeadAPIServer
// for forward compatibility.
type MeadAPIServer interface {
	Version(context.Context, *Version_Request) (*Version_Response, error)
	mustEmbedUnimplementedMeadAPIServer()
}

// UnimplementedMeadAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeadAPIServer struct{}

func (UnimplementedMeadAPIServer) Version(context.Context, *Version_Request) (*Version_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedMeadAPIServer) mustEmbedUnimplementedMeadAPIServer() {}
func (UnimplementedMeadAPIServer) testEmbeddedByValue()                 {}

// UnsafeMeadAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeadAPIServer will
// result in compilation errors.
type UnsafeMeadAPIServer interface {
	mustEmbedUnimplementedMeadAPIServer()
}

func RegisterMeadAPIServer(s grpc.ServiceRegistrar, srv MeadAPIServer) {
	// If the following call panics, it indicates UnimplementedMeadAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeadAPI_ServiceDesc, srv)
}

func _MeadAPI_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Version_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeadAPIServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeadAPI_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeadAPIServer).Version(ctx, req.(*Version_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MeadAPI_ServiceDesc is the grpc.ServiceDesc for MeadAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeadAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mead_api.MeadAPI",
	HandlerType: (*MeadAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _MeadAPI_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mead_api.proto",
}
