// Code generated by RedSock CLI. DO NOT EDIT.

package config

import (
	"time"
)

type EnvironmentConfig struct {
	Address      string
	APIToken     string
	DialTimeout  time.Duration
	LogFormat    string
	LogLevel     string
	ProxyAddress string
	ProxyPort    int
	ReadTimeout  time.Duration
}

const (
	LogFormat_Json = "JSON"
	LogFormat_Text = "TEXT"
)

const (
	LogLevel_Trace = "Trace"
	LogLevel_Debug = "Debug"
	LogLevel_Info  = "Info"
	LogLevel_Warn  = "Warn"
	LogLevel_Error = "Error"
	LogLevel_Fatal = "Fatal"
	LogLevel_Panic = "Panic"
)
